#!/usr/bin/env python3
# /// script
# dependencies = ["numpy", "scipy", "torch", "plotly"]
# ///
"""2D Euler-Maruyama FK-label and Algorithm 2 audit for Claims 3 and 6.

This script is intentionally scoped to the two claims that were under-scored
after the stronger paper-scale audit: the FK label decomposition and the
offline-MC/online-PINN training procedure.  Unlike the first pass, the labels
below are generated by true 2D Brownian Euler-Maruyama simulation, not by
adding exact-plus-noise labels.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
from scipy import stats
import torch


CENTER = np.array([0.5, 0.5], dtype=np.float64)
RADIUS = 0.5


def seed_all(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def device_auto() -> torch.device:
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def sample_disk(n: int, rng: np.random.Generator) -> np.ndarray:
    theta = rng.random(n) * 2.0 * math.pi
    r = np.sqrt(rng.random(n)) * RADIUS
    return np.stack([0.5 + r * np.cos(theta), 0.5 + r * np.sin(theta)], axis=1)


def sample_square(n: int, rng: np.random.Generator) -> np.ndarray:
    return rng.random((n, 2))


def sample_disk_boundary(n: int, rng: np.random.Generator) -> np.ndarray:
    theta = rng.random(n) * 2.0 * math.pi
    return np.stack([0.5 + RADIUS * np.cos(theta), 0.5 + RADIUS * np.sin(theta)], axis=1)


def sample_square_boundary(n: int, rng: np.random.Generator) -> np.ndarray:
    m = max(1, n // 4)
    t = rng.random(m)
    pts = [
        np.stack([np.zeros_like(t), t], axis=1),
        np.stack([np.ones_like(t), t], axis=1),
        np.stack([t, np.zeros_like(t)], axis=1),
        np.stack([t, np.ones_like(t)], axis=1),
    ]
    return np.concatenate(pts, axis=0)[:n]


def exact_np(problem: str, x: np.ndarray) -> np.ndarray:
    if problem == "met":
        r2 = np.sum((x - CENTER) ** 2, axis=1)
        return np.maximum((RADIUS**2 - r2) / 2.0, 0.0)
    if problem == "committor":
        return x[:, 0]
    raise ValueError(problem)


def exact_torch(problem: str, x: torch.Tensor) -> torch.Tensor:
    if problem == "met":
        r2 = torch.sum((x - 0.5) ** 2, dim=1, keepdim=True)
        return torch.clamp((RADIUS**2 - r2) / 2.0, min=0.0)
    if problem == "committor":
        return x[:, :1]
    raise ValueError(problem)


def em_met_paths(x: np.ndarray, dt: float, n_mc: int, t_max: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    n = x.shape[0]
    pos = np.repeat(x, n_mc, axis=0).astype(np.float64, copy=True)
    alive = np.ones(pos.shape[0], dtype=bool)
    labels = np.full(pos.shape[0], t_max, dtype=np.float64)
    times = np.zeros(pos.shape[0], dtype=np.float64)
    step_scale = math.sqrt(dt)
    for _ in range(int(math.ceil(t_max / dt))):
        idx = np.flatnonzero(alive)
        if idx.size == 0:
            break
        pos[idx] += step_scale * rng.standard_normal((idx.size, 2))
        times[idx] += dt
        exited = np.sum((pos[idx] - CENTER) ** 2, axis=1) >= RADIUS**2
        if np.any(exited):
            dead = idx[exited]
            labels[dead] = times[dead]
            alive[dead] = False
    return labels.reshape(n, n_mc)


def square_boundary_value(pos: np.ndarray) -> np.ndarray:
    # Dirichlet boundary for the harmonic committor q(x, y)=x on the whole square.
    return np.clip(pos[:, 0], 0.0, 1.0)


def em_committor_paths(x: np.ndarray, dt: float, n_mc: int, t_max: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    n = x.shape[0]
    pos = np.repeat(x, n_mc, axis=0).astype(np.float64, copy=True)
    alive = np.ones(pos.shape[0], dtype=bool)
    labels = np.zeros(pos.shape[0], dtype=np.float64)
    step_scale = math.sqrt(dt)
    for _ in range(int(math.ceil(t_max / dt))):
        idx = np.flatnonzero(alive)
        if idx.size == 0:
            break
        pos[idx] += step_scale * rng.standard_normal((idx.size, 2))
        exited = (pos[idx, 0] <= 0.0) | (pos[idx, 0] >= 1.0) | (pos[idx, 1] <= 0.0) | (pos[idx, 1] >= 1.0)
        if np.any(exited):
            dead = idx[exited]
            labels[dead] = square_boundary_value(pos[dead])
            alive[dead] = False
    if np.any(alive):
        labels[alive] = square_boundary_value(pos[alive])
    return labels.reshape(n, n_mc)


def laplacian(model: torch.nn.Module, x: torch.Tensor) -> torch.Tensor:
    x = x.detach().clone().requires_grad_(True)
    y = model(x)
    grad = torch.autograd.grad(y, x, torch.ones_like(y), create_graph=True)[0]
    parts = []
    for j in range(2):
        g = grad[:, j : j + 1]
        h = torch.autograd.grad(g, x, torch.ones_like(g), create_graph=True)[0][:, j : j + 1]
        parts.append(h)
    return parts[0] + parts[1]


class MLP(torch.nn.Module):
    def __init__(self, width: int, hidden: int):
        super().__init__()
        layers: list[torch.nn.Module] = [torch.nn.Linear(2, width), torch.nn.Tanh()]
        for _ in range(hidden - 1):
            layers += [torch.nn.Linear(width, width), torch.nn.Tanh()]
        layers.append(torch.nn.Linear(width, 1))
        self.net = torch.nn.Sequential(*layers)
        for module in self.modules():
            if isinstance(module, torch.nn.Linear):
                torch.nn.init.xavier_uniform_(module.weight)
                torch.nn.init.zeros_(module.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


@dataclass
class TrainCfg:
    width: int
    hidden: int
    steps: int
    n_int: int
    n_bc: int
    batch: int
    lr: float


def residual(problem: str, model: torch.nn.Module, x: torch.Tensor) -> torch.Tensor:
    lap = laplacian(model, x)
    if problem == "met":
        return -0.5 * lap - 1.0
    if problem == "committor":
        return lap
    raise ValueError(problem)


def train_stage2(problem: str, xfk: np.ndarray, yfk: np.ndarray, cfg: TrainCfg, seed: int, device: torch.device) -> dict:
    seed_all(seed)
    rng = np.random.default_rng(seed + 900)
    model = MLP(cfg.width, cfg.hidden).to(device)
    if problem == "met":
        xi_np = sample_disk(cfg.n_int, rng)
        xb_np = sample_disk_boundary(cfg.n_bc, rng)
    else:
        xi_np = sample_square(cfg.n_int, rng)
        xb_np = sample_square_boundary(cfg.n_bc, rng)
    xi = torch.tensor(xi_np, dtype=torch.float32, device=device)
    xb = torch.tensor(xb_np, dtype=torch.float32, device=device)
    yb = exact_torch(problem, xb)
    xfk_t = torch.tensor(xfk, dtype=torch.float32, device=device)
    yfk_t = torch.tensor(yfk[:, None], dtype=torch.float32, device=device)
    logvars = torch.nn.Parameter(torch.zeros(3, device=device))
    opt = torch.optim.Adam(list(model.parameters()) + [logvars], lr=cfg.lr)
    hist: list[dict] = []
    for step in range(cfg.steps):
        ib = torch.randint(0, xi.shape[0], (min(cfg.batch, xi.shape[0]),), device=device)
        bb = torch.randint(0, xb.shape[0], (min(max(64, cfg.batch // 4), xb.shape[0]),), device=device)
        fb = torch.randint(0, xfk_t.shape[0], (min(max(64, cfg.batch // 4), xfk_t.shape[0]),), device=device)
        opt.zero_grad(set_to_none=True)
        lpde = torch.mean(residual(problem, model, xi[ib]) ** 2)
        lbc = torch.mean((model(xb[bb]) - yb[bb]) ** 2)
        lfk = torch.mean((model(xfk_t[fb]) - yfk_t[fb]) ** 2)
        s = torch.clamp(logvars, -8.0, 8.0)
        loss = torch.exp(-s[0]) * lpde + s[0] + torch.exp(-s[1]) * lbc + s[1] + torch.exp(-s[2]) * lfk + s[2]
        loss.backward()
        opt.step()
        with torch.no_grad():
            logvars.clamp_(-8.0, 8.0)
        if step in {0, cfg.steps // 4, cfg.steps // 2, cfg.steps - 1}:
            hist.append(
                {
                    "problem": problem,
                    "step": step,
                    "total": float(loss.detach().cpu()),
                    "lpde": float(lpde.detach().cpu()),
                    "lbc": float(lbc.detach().cpu()),
                    "lfk": float(lfk.detach().cpu()),
                    "s_pde": float(logvars[0].detach().cpu()),
                    "s_bc": float(logvars[1].detach().cpu()),
                    "s_fk": float(logvars[2].detach().cpu()),
                }
            )
    test_np = sample_disk(5000, rng) if problem == "met" else sample_square(5000, rng)
    test = torch.tensor(test_np, dtype=torch.float32, device=device)
    with torch.no_grad():
        y = exact_torch(problem, test)
        pred = model(test)
        rel = torch.linalg.norm(pred - y) / torch.linalg.norm(y)
    return {
        "problem": problem,
        "history": hist,
        "rel_l2": float(rel.detach().cpu()),
        "logvars": [float(v) for v in logvars.detach().cpu()],
        "weights": [float(math.exp(-v)) for v in logvars.detach().cpu()],
    }


def claim3(mode: str, out: Path) -> dict:
    rng = np.random.default_rng(2026)
    if mode == "smoke":
        n_x, n_mc, dts = 80, 250, [0.008, 0.004, 0.002]
        noise_mc = 800
    else:
        n_x, n_mc, dts = 160, 700, [0.008, 0.004, 0.002, 0.001]
        noise_mc = 1800
    x_met = sample_disk(n_x, rng)
    x_com = sample_square(n_x, rng)
    bias_rows: list[dict] = []
    for problem, x, t_max in [("met", x_met, 1.2), ("committor", x_com, 1.5)]:
        exact = exact_np(problem, x)
        for k, dt in enumerate(dts):
            paths = em_met_paths(x, dt, n_mc, t_max, 1000 + k) if problem == "met" else em_committor_paths(x, dt, n_mc, t_max, 2000 + k)
            mean = paths.mean(axis=1)
            bias = np.abs(mean - exact)
            bias_rows.append(
                {
                    "problem": problem,
                    "dt": dt,
                    "mean_abs_bias": float(bias.mean()),
                    "bias_over_sqrt_dt": float(bias.mean() / math.sqrt(dt)),
                    "max_abs_bias": float(bias.max()),
                    "n_x": n_x,
                    "n_mc": n_mc,
                }
            )
    noise_rows: list[dict] = []
    for problem, sampler, labeler, t_max, seed in [
        ("met", sample_disk, em_met_paths, 1.2, 3100),
        ("committor", sample_square, em_committor_paths, 1.5, 4100),
    ]:
        x = sampler(72 if mode == "smoke" else 96, rng)
        paths = labeler(x, 0.0015 if mode == "smoke" else 0.001, noise_mc, t_max, seed)
        zeta = (paths - paths.mean(axis=1, keepdims=True)).reshape(-1)
        absz = np.abs(zeta)
        thresholds = np.quantile(absz, np.linspace(0.55, 0.96, 9))
        probs = np.array([(absz > t).mean() for t in thresholds])
        mask = probs > 0
        lin_t = stats.linregress(thresholds[mask], np.log(probs[mask]))
        lin_t2 = stats.linregress(thresholds[mask] ** 2, np.log(probs[mask]))
        noise_rows.append(
            {
                "problem": problem,
                "std_zeta": float(zeta.std()),
                "mean_zeta": float(zeta.mean()),
                "exp_moment_lambda": 4.0,
                "exp_moment": float(np.mean(np.exp(4.0 * absz))),
                "tail_slope_t": float(lin_t.slope),
                "tail_corr_t": float(lin_t.rvalue),
                "tail_slope_t2": float(lin_t2.slope),
                "tail_corr_t2": float(lin_t2.rvalue),
                "bounded_support_max": float(absz.max()),
            }
        )
    # Exponential exit-time tail for the MET truncation term.
    exit_paths = em_met_paths(sample_disk(120 if mode == "smoke" else 220, rng), 0.0015 if mode == "smoke" else 0.001, 900 if mode == "smoke" else 1600, 1.2, 5100)
    thresholds = np.array([0.12, 0.18, 0.24, 0.30, 0.36, 0.42])
    surv = np.array([(exit_paths.reshape(-1) > t).mean() for t in thresholds])
    tail_fit = stats.linregress(thresholds[surv > 0], np.log(surv[surv > 0]))
    for row in noise_rows:
        if row["problem"] == "met":
            row["exit_tail_rate"] = float(-tail_fit.slope)
            row["exit_tail_corr"] = float(tail_fit.rvalue)
    out.mkdir(parents=True, exist_ok=True)
    write_csv(out / "claim3_2d_em_bias.csv", bias_rows)
    write_csv(out / "claim3_2d_em_noise.csv", noise_rows)
    fig = go.Figure()
    for problem in sorted({r["problem"] for r in bias_rows}):
        rows = [r for r in bias_rows if r["problem"] == problem]
        fig.add_trace(go.Scatter(x=[r["dt"] for r in rows], y=[r["mean_abs_bias"] for r in rows], mode="lines+markers", name=problem))
    fig.update_layout(title="2D Euler-Maruyama FK bias vs dt", xaxis_title="dt", yaxis_title="mean |bias|", xaxis_type="log", yaxis_type="log")
    fig.write_html(out / "claim3_2d_em_bias.html", include_plotlyjs="cdn")
    slopes = {}
    for problem in sorted({r["problem"] for r in bias_rows}):
        rows = [r for r in bias_rows if r["problem"] == problem]
        fit = stats.linregress(np.log([r["dt"] for r in rows]), np.log([r["mean_abs_bias"] for r in rows]))
        slopes[problem] = float(fit.slope)
    summary = {"bias_slopes": slopes, "noise": noise_rows}
    print("CLAIM3_SUMMARY", json.dumps(summary, sort_keys=True))
    return summary


def claim6(mode: str, out: Path, device: torch.device) -> dict:
    rng = np.random.default_rng(6060)
    if mode == "smoke":
        n_fk, n_mc, dt, steps, width = 120, 200, 0.0025, 260, 48
    else:
        n_fk, n_mc, dt, steps, width = 240, 450, 0.0015, 560, 72
    cfg = TrainCfg(width=width, hidden=4, steps=steps, n_int=2200 if mode == "full" else 900, n_bc=600 if mode == "full" else 260, batch=384, lr=2.5e-3)
    stage_rows: list[dict] = []
    history_rows: list[dict] = []
    results = []
    for problem, sampler, labeler, t_max, seed in [
        ("met", sample_disk, em_met_paths, 1.2, 7000),
        ("committor", sample_square, em_committor_paths, 1.5, 8000),
    ]:
        xfk = sampler(n_fk, rng)
        paths = labeler(xfk, dt, n_mc, t_max, seed)
        yfk = paths.mean(axis=1)
        exact = exact_np(problem, xfk)
        label_rmse = float(np.sqrt(np.mean((yfk - exact) ** 2)))
        label_bias = float(np.mean(yfk - exact))
        stage_rows.append(
            {
                "problem": problem,
                "stage": "offline_em",
                "N_FK": n_fk,
                "N_MC": n_mc,
                "dt": dt,
                "T_max": t_max,
                "label_rmse_vs_exact": label_rmse,
                "mean_label_bias": label_bias,
                "label_std_mean": float(paths.std(axis=1).mean()),
            }
        )
        print("STAGE1", problem, "N_FK", n_fk, "N_MC", n_mc, "dt", dt, "rmse", label_rmse)
        res = train_stage2(problem, xfk, yfk, cfg, seed + 17, device)
        results.append(res)
        for row in res["history"]:
            history_rows.append(row)
        stage_rows.append(
            {
                "problem": problem,
                "stage": "online_uncertainty_pinn",
                "N_FK": n_fk,
                "N_MC": n_mc,
                "dt": dt,
                "T_max": t_max,
                "label_rmse_vs_exact": label_rmse,
                "mean_label_bias": label_bias,
                "label_std_mean": float(paths.std(axis=1).mean()),
                "rel_l2": res["rel_l2"],
                "w_pde": res["weights"][0],
                "w_bc": res["weights"][1],
                "w_fk": res["weights"][2],
                "s_pde": res["logvars"][0],
                "s_bc": res["logvars"][1],
                "s_fk": res["logvars"][2],
            }
        )
        print("STAGE2", problem, "rel_l2", res["rel_l2"], "weights", res["weights"])
    out.mkdir(parents=True, exist_ok=True)
    write_csv(out / "claim6_2d_algorithm.csv", stage_rows)
    write_csv(out / "claim6_2d_training_history.csv", history_rows)
    fig = go.Figure()
    for problem in sorted({r["problem"] for r in history_rows}):
        rows = [r for r in history_rows if r["problem"] == problem]
        fig.add_trace(go.Scatter(x=[r["step"] for r in rows], y=[r["total"] for r in rows], mode="lines+markers", name=f"{problem} total"))
        fig.add_trace(go.Scatter(x=[r["step"] for r in rows], y=[r["lfk"] for r in rows], mode="lines+markers", name=f"{problem} FK loss"))
    fig.update_layout(title="2D Algorithm 2 uncertainty-weighted training", xaxis_title="step", yaxis_title="loss", yaxis_type="log")
    fig.write_html(out / "claim6_2d_training.html", include_plotlyjs="cdn")
    summary = {
        "stage_rows": stage_rows,
        "rel_l2": {r["problem"]: r["rel_l2"] for r in results},
        "weights": {r["problem"]: r["weights"] for r in results},
    }
    print("CLAIM6_SUMMARY", json.dumps(summary, sort_keys=True))
    return summary


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    fieldnames: list[str] = []
    for row in rows:
        for key in row.keys():
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["smoke", "full"], default="full")
    parser.add_argument("--sections", default="all", help="Comma-separated c3,c6,all")
    parser.add_argument("--outdir", default="results/claim3_6_2d_full")
    args = parser.parse_args()
    out = Path(args.outdir)
    device = device_auto()
    print("DEVICE", device)
    sections = {"c3", "c6"} if args.sections == "all" else {s.strip() for s in args.sections.split(",") if s.strip()}
    summary: dict = {"mode": args.mode, "device": str(device)}
    if "c3" in sections:
        summary["claim3"] = claim3(args.mode, out)
    if "c6" in sections:
        summary["claim6"] = claim6(args.mode, out, device)
    out.mkdir(parents=True, exist_ok=True)
    (out / "claim3_6_2d_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True))
    print("SUMMARY", json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    main()
